dependencies:
  - name: mariadb
    version: 5.x.x
    repository: https://kubernetes-charts.storage.googleapis.com/
    condition: mysql.enabled,global.mysql.enabled
  - name: elasticsearch
    version: 6.x
    repository: https://helm.elastic.co/
    condition: elasticsearch.enabled,global.elasticsearch.enabled
